# Prepare Chicago Crime Data for a GitHub Repository

- Original Notebook Source: https://github.com/coding-dojo-data-science/preparing-chicago-crime-data
- Updated 11/17/22

>- This notebook will process a "Crimes - 2001 to Preset.csv" crime file in your Downloads folder and save it as smaller .csv's in a new "Data/Chicago/" folder inside this notebook's folder/repo.

# INSTRUCTIONS

- 1) Go to the Chicago Data Portal's page for ["Crimes - 2001 to Preset"](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2).

- 2) Click on the Export button on the top right and select CSV. 
    - Save the file to your Downloads folder instead of your repository. **The file is too big for a repository.**
    
    
    
- 3) Wait for the full file to download. 
    - It is very large (over >1.7GB and may take several minutes to fully download.)
    
    
- 4) Once the download is complete, change `RAW_FILE` variable below to match the filepath to the downloaded file.

## ðŸš¨ Set the correct `RAW_FILE` path

- The cell below will attempt to check your Downloads folder for any file with a name that contains "Crimes_-_2001_to_Present".
    - If you know the file path already, you can skip the next cell and just manually set the RAW_FILE variable in the following code cell.

In [1]:
## Run the cell below to attempt to programmatically find your crime file
import os,glob

## Getting the home folder from environment variables
home_folder = os.environ['HOME']
# print("- Your Home Folder is: " + home_folder)

## Check for downloads folder
if 'Downloads' in os.listdir(home_folder):
    
    
    # Print the Downloads folder path
    dl_folder = os.path.abspath(os.path.join(home_folder,'Downloads'))
    print(f"- Your Downloads folder is '{dl_folder}/'\n")
    
    ## checking for crime files using glob
    crime_files = sorted(glob.glob(dl_folder+'/**/Crimes_-_2001_to_Present*',recursive=True))
    
    # If more than 
    if len(crime_files)==1:
        RAW_FILE = crime_files[0]
        
    elif len(crime_files)>1:
        print('[i] The following files were found:')
        
        for i, fname in enumerate(crime_files):
            print(f"\tcrime_files[{i}] = '{fname}'")
        print(f'\n- Please fill in the RAW_FILE variable in the code cell below with the correct filepath.')

else:
    print(f'[!] Could not programmatically find your downloads folder.')
    print('- Try using Finder (on Mac) or File Explorer (Windows) to navigate to your Downloads folder.')

- Your Downloads folder is '/Users/yawagipong/Downloads/'

In [2]:
## (Required) MAKE SURE TO CHANGE THIS VARIABLE TO MATCH YOUR LOCAL FILE NAME
RAW_FILE = "/Users/yawagipong/Downloads/crimes.csv" #(or slice correct index from the crime_files list)

if RAW_FILE == "YOUR FILEPATH HERE":
	raise Exception("You must update the RAW_FILE variable to match your local filepath.")
	
RAW_FILE

'/Users/yawagipong/Downloads/crimes.csv'

In [3]:
## (Optional) SET THE FOLDER FOR FINAL FILES
OUTPUT_FOLDER = 'Data/Chicago/'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# ðŸ”„ Full Workflow

- Now that your RAW_FILE variable is set either:
    - On the toolbar, click on the Kernel menu > "Restart and Run All".
    - OR click on this cell first, then on the toolbar click on the "Cell" menu > "Run All Below"

In [4]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format',lambda x: f"{x:,.2f}")

In [5]:
chicago_full = pd.read_csv(RAW_FILE)
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,924,9.00,12.00,61.00,08B,"1,165,074.00","1,875,917.00",2015,02/10/2018 03:50:01 PM,41.82,-87.67,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,1511,15.00,29.00,25.00,06,"1,138,875.00","1,904,869.00",2015,02/10/2018 03:50:01 PM,41.90,-87.77,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,631,6.00,8.00,44.00,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.00,35.00,21.00,18,"1,152,037.00","1,920,384.00",2015,02/10/2018 03:50:01 PM,41.94,-87.72,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,1522,15.00,28.00,25.00,08A,"1,141,706.00","1,900,086.00",2015,02/10/2018 03:50:01 PM,41.88,-87.76,"(41.881903443, -87.755121152)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7748353,12847575,JF420478,09/01/2022 05:00:00 AM,005XX W SURF ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,1934,19.00,44.00,6.00,26,"1,172,497.00","1,919,410.00",2022,01/03/2023 03:46:28 PM,41.93,-87.64,"(41.934304581, -87.641484982)"
7748354,12847801,JF420319,07/08/2022 12:00:00 AM,114XX S PRAIRIE AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,STREET,False,False,531,5.00,9.00,49.00,11,"1,179,966.00","1,828,818.00",2022,01/03/2023 03:46:28 PM,41.69,-87.62,"(41.685543881, -87.616812541)"
7748355,12847324,JF420102,09/27/2022 11:00:00 AM,023XX E 70TH ST,0810,THEFT,OVER $500,RESIDENCE,False,False,331,3.00,5.00,43.00,06,"1,193,181.00","1,859,005.00",2022,01/03/2023 03:46:28 PM,41.77,-87.57,"(41.768068052, -87.567452932)"
7748356,12847570,JF420427,09/03/2022 10:25:00 AM,052XX W CARMEN AVE,2021,NARCOTICS,POSSESS - BARBITURATES,RESIDENCE - YARD (FRONT / BACK),True,False,1623,16.00,45.00,11.00,18,"1,140,553.00","1,933,418.00",2022,01/03/2023 03:46:28 PM,41.97,-87.76,"(41.973391184, -87.758534512)"
7748357,12840464,JF411839,09/26/2022 07:20:00 PM,0000X N MASON AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,SIDEWALK,True,False,1513,15.00,29.00,25.00,15,"1,136,773.00","1,899,652.00",2022,01/03/2023 03:46:28 PM,41.88,-87.77,"(41.880802263, -87.773245737)"

In [6]:
# explicitly setting the format to speed up pd.to_datetime
date_format = "%m/%d/%Y %H:%M:%S %p"


### Demonstrating/testing date_format
example = chicago_full.loc[0,'Date']
display(example)
pd.to_datetime(example,format=date_format)

'09/05/2015 01:30:00 PM'

Timestamp('2015-09-05 01:30:00')

In [7]:
# this cell can take up to 1 min to run
chicago_full['Datetime'] = pd.to_datetime(chicago_full['Date'], format=date_format)
chicago_full = chicago_full.sort_values('Datetime')
chicago_full = chicago_full.set_index('Datetime')
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
Datetime,,,,,,,,,,,,,,,,,,,,,,
2001-01-01 01:00:00,1324743,G001083,01/01/2001 01:00:00 PM,005XX E 63 ST,1626,GAMBLING,ILLEGAL ILL LOTTERY,STREET,True,False,313,3.00,NaN,NaN,19,"1,180,999.00","1,863,398.00",2001,08/17/2015 03:03:40 PM,41.78,-87.61,"(41.780411868, -87.611970027)"
2001-01-01 01:00:00,1311269,G001223,01/01/2001 01:00:00 AM,076XX S COLFAX AV,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,421,4.00,NaN,NaN,14,"1,194,808.00","1,854,873.00",2001,08/17/2015 03:03:40 PM,41.76,-87.56,"(41.756689633, -87.561625217)"
2001-01-01 01:00:00,1315701,G003835,01/01/2001 01:00:00 PM,011XX S PULASKI RD,041A,BATTERY,AGGRAVATED: HANDGUN,RESIDENCE,False,False,1132,11.00,NaN,NaN,04B,"1,149,936.00","1,894,501.00",2001,08/17/2015 03:03:40 PM,41.87,-87.73,"(41.866421432, -87.72504577)"
2001-01-01 01:00:00,1410662,G123231,01/01/2001 01:00:00 AM,007XX E 50 PL,0560,ASSAULT,SIMPLE,RESIDENCE,False,True,223,2.00,NaN,NaN,08A,"1,181,985.00","1,871,730.00",2001,08/17/2015 03:03:40 PM,41.80,-87.61,"(41.803252854, -87.608097536)"
2001-01-01 01:00:00,1315458,G005079,01/01/2001 01:00:00 AM,016XX N HUMBOLDT BL,0820,THEFT,$500 AND UNDER,STREET,False,False,1421,14.00,NaN,NaN,06,"1,156,090.00","1,910,543.00",2001,08/17/2015 03:03:40 PM,41.91,-87.70,"(41.910320325, -87.702020443)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 12:55:00,12996428,JG168989,02/28/2023 12:55:00 PM,003XX W CHICAGO AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,GAS STATION,False,False,1823,18.00,27.00,8.00,07,"1,173,639.00","1,905,658.00",2023,03/07/2023 03:47:26 PM,41.90,-87.64,"(41.896543094, -87.637698101)"
2023-02-28 12:56:00,12998570,JG171603,02/28/2023 12:56:00 AM,012XX W GRACE ST,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1923,19.00,44.00,6.00,14,"1,167,374.00","1,925,466.00",2023,03/07/2023 03:47:26 PM,41.95,-87.66,"(41.951034425, -87.660137054)"
2023-02-28 12:59:00,12996529,JG169009,02/28/2023 12:59:00 PM,024XX W GRENSHAW ST,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,APARTMENT,False,False,1135,11.00,28.00,28.00,17,"1,160,223.00","1,894,973.00",2023,03/07/2023 03:47:26 PM,41.87,-87.69,"(41.867510416, -87.687268033)"
2023-02-28 12:59:00,12996466,JG169038,02/28/2023 12:59:00 PM,039XX W 76TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,SIDEWALK,True,True,833,8.00,18.00,70.00,15,"1,151,357.00","1,853,895.00",2023,03/07/2023 03:47:26 PM,41.75,-87.72,"(41.754965064, -87.720891432)"
2023-02-28 12:59:00,12995963,JG168525,02/28/2023 12:59:00 AM,013XX N AVERS AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,2535,25.00,26.00,23.00,14,"1,150,465.00","1,908,736.00",2023,03/07/2023 03:47:26 PM,41.91,-87.72,"(41.905473493, -87.722731903)"

In [8]:
(chicago_full.isna().sum()/len(chicago_full)).round(2)

ID                     0.00
Case Number            0.00
Date                   0.00
Block                  0.00
IUCR                   0.00
Primary Type           0.00
Description            0.00
Location Description   0.00
Arrest                 0.00
Domestic               0.00
Beat                   0.00
District               0.00
Ward                   0.08
Community Area         0.08
FBI Code               0.00
X Coordinate           0.01
Y Coordinate           0.01
Year                   0.00
Updated On             0.00
Latitude               0.01
Longitude              0.01
Location               0.01
dtype: float64

## Separate the Full Dataset by Years

In [9]:
# save the years for every crime
chicago_full["Year"] = chicago_full.index.year
chicago_full["Year"] = chicago_full["Year"].astype(str)
chicago_full["Year"].value_counts()

2002    486801
2001    485872
2003    475979
2004    469420
2005    453769
2006    448174
2007    437081
2008    427159
2009    392816
2010    370492
2011    351959
2012    336260
2013    307462
2014    275725
2016    269778
2017    269049
2018    268748
2015    264737
2019    261213
2022    237203
2020    212041
2021    208439
2023     38181
Name: Year, dtype: int64

In [10]:
## Dropping unneeded columns to reduce file size
drop_cols = ["X Coordinate","Y Coordinate", "Community Area","FBI Code",
             "Case Number","Updated On",'Block','Location','IUCR']

In [11]:
# save final df
chicago_final = chicago_full.drop(columns=drop_cols).sort_index()#.reset_index()
chicago_final

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Year,Latitude,Longitude
Datetime,,,,,,,,,,,,,
2001-01-01 01:00:00,1324743,01/01/2001 01:00:00 PM,GAMBLING,ILLEGAL ILL LOTTERY,STREET,True,False,313,3.00,NaN,2001,41.78,-87.61
2001-01-01 01:00:00,1311269,01/01/2001 01:00:00 AM,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,421,4.00,NaN,2001,41.76,-87.56
2001-01-01 01:00:00,1315701,01/01/2001 01:00:00 PM,BATTERY,AGGRAVATED: HANDGUN,RESIDENCE,False,False,1132,11.00,NaN,2001,41.87,-87.73
2001-01-01 01:00:00,1410662,01/01/2001 01:00:00 AM,ASSAULT,SIMPLE,RESIDENCE,False,True,223,2.00,NaN,2001,41.80,-87.61
2001-01-01 01:00:00,1315458,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,STREET,False,False,1421,14.00,NaN,2001,41.91,-87.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 12:55:00,12996428,02/28/2023 12:55:00 PM,MOTOR VEHICLE THEFT,AUTOMOBILE,GAS STATION,False,False,1823,18.00,27.00,2023,41.90,-87.64
2023-02-28 12:56:00,12998570,02/28/2023 12:56:00 AM,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1923,19.00,44.00,2023,41.95,-87.66
2023-02-28 12:59:00,12996529,02/28/2023 12:59:00 PM,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,APARTMENT,False,False,1135,11.00,28.00,2023,41.87,-87.69
2023-02-28 12:59:00,12996466,02/28/2023 12:59:00 PM,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,SIDEWALK,True,True,833,8.00,18.00,2023,41.75,-87.72
2023-02-28 12:59:00,12995963,02/28/2023 12:59:00 AM,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,2535,25.00,26.00,2023,41.91,-87.72

In [12]:
chicago_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 7748358 entries, 2001-01-01 01:00:00 to 2023-02-28 12:59:00
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Date                  object
 2   Primary Type          object
 3   Description           object
 4   Location Description  object
 5   Arrest                bool
 6   Domestic              bool
 7   Beat                  int64
 8   District              float64
 9   Ward                  float64
 10  Year                  object
 11  Latitude              float64
 12  Longitude             float64
dtypes: bool(2), float64(4), int64(2), object(5)
memory usage: 724.2+ MB

In [13]:
chicago_final.memory_usage(deep=True).astype(float)

Index                   61,986,864.00
ID                      61,986,864.00
Date                   612,120,282.00
Primary Type           519,382,549.00
Description            567,086,862.00
Location Description   528,105,858.00
Arrest                   7,748,358.00
Domestic                 7,748,358.00
Beat                    61,986,864.00
District                61,986,864.00
Ward                    61,986,864.00
Year                   472,649,838.00
Latitude                61,986,864.00
Longitude               61,986,864.00
dtype: float64

In [14]:
# unique # of year bins
year_bins = chicago_final['Year'].astype(str).unique()
year_bins

array(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023'],
      dtype=object)

In [15]:
FINAL_DROP = ['Datetime','Year']#,'Location Description']

In [16]:
## set save location 

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
print(f"[i] Saving .csv's to {OUTPUT_FOLDER}")
## loop through years
for year in year_bins:
    
    ## save temp slices of dfs to save.
    temp_df = chicago_final.loc[ year]
    temp_df = temp_df.reset_index(drop=False)
    temp_df = temp_df.drop(columns=FINAL_DROP)

    # save as csv to output folder
    fname_temp = f"{OUTPUT_FOLDER}Chicago-Crime_{year}.csv"#.gz
    temp_df.to_csv(fname_temp,index=False)

    print(f"- Succesfully saved {fname_temp}")

[i] Saving .csv's to Data/Chicago/
- Succesfully saved Data/Chicago/Chicago-Crime_2001.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2002.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2003.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2004.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2005.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2006.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2007.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2008.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2009.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2010.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2011.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2012.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2013.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2014.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2015.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2016.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2017.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2018.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2019.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2020.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2021.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2022.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2023.csv

In [17]:
saved_files = sorted(glob.glob(OUTPUT_FOLDER+'*.*csv'))
saved_files

['Data/Chicago/Chicago-Crime_2001.csv',
 'Data/Chicago/Chicago-Crime_2002.csv',
 'Data/Chicago/Chicago-Crime_2003.csv',
 'Data/Chicago/Chicago-Crime_2004.csv',
 'Data/Chicago/Chicago-Crime_2005.csv',
 'Data/Chicago/Chicago-Crime_2006.csv',
 'Data/Chicago/Chicago-Crime_2007.csv',
 'Data/Chicago/Chicago-Crime_2008.csv',
 'Data/Chicago/Chicago-Crime_2009.csv',
 'Data/Chicago/Chicago-Crime_2010.csv',
 'Data/Chicago/Chicago-Crime_2011.csv',
 'Data/Chicago/Chicago-Crime_2012.csv',
 'Data/Chicago/Chicago-Crime_2013.csv',
 'Data/Chicago/Chicago-Crime_2014.csv',
 'Data/Chicago/Chicago-Crime_2015.csv',
 'Data/Chicago/Chicago-Crime_2016.csv',
 'Data/Chicago/Chicago-Crime_2017.csv',
 'Data/Chicago/Chicago-Crime_2018.csv',
 'Data/Chicago/Chicago-Crime_2019.csv',
 'Data/Chicago/Chicago-Crime_2020.csv',
 'Data/Chicago/Chicago-Crime_2021.csv',
 'Data/Chicago/Chicago-Crime_2022.csv',
 'Data/Chicago/Chicago-Crime_2023.csv',
 'Data/Chicago/crimes.csv']

In [18]:
## create a README.txt for the zip files
readme = """Source URL: 
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])
"""
print(readme)


with open(f"{OUTPUT_FOLDER}README.txt",'w') as f:
    f.write(readme)

Source URL:
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])

## Confirmation

- Follow the example usage above to test if your files were created successfully.

In [19]:
# get list of files from folder
crime_files = sorted(glob.glob(OUTPUT_FOLDER+"*.csv"))
df = pd.concat([pd.read_csv(f) for f in crime_files])
df

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Latitude,Longitude,Case Number,Block,IUCR,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Location
0,1324743,01/01/2001 01:00:00 PM,GAMBLING,ILLEGAL ILL LOTTERY,STREET,True,False,313,3.00,NaN,41.78,-87.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1311269,01/01/2001 01:00:00 AM,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,421,4.00,NaN,41.76,-87.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1315701,01/01/2001 01:00:00 PM,BATTERY,AGGRAVATED: HANDGUN,RESIDENCE,False,False,1132,11.00,NaN,41.87,-87.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1410662,01/01/2001 01:00:00 AM,ASSAULT,SIMPLE,RESIDENCE,False,True,223,2.00,NaN,41.80,-87.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1315458,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,STREET,False,False,1421,14.00,NaN,41.91,-87.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7748353,12847575,09/01/2022 05:00:00 AM,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,1934,19.00,44.00,41.93,-87.64,JF420478,005XX W SURF ST,2825,6.00,26,"1,172,497.00","1,919,410.00","2,022.00",01/03/2023 03:46:28 PM,"(41.934304581, -87.641484982)"
7748354,12847801,07/08/2022 12:00:00 AM,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,STREET,False,False,531,5.00,9.00,41.69,-87.62,JF420319,114XX S PRAIRIE AVE,1130,49.00,11,"1,179,966.00","1,828,818.00","2,022.00",01/03/2023 03:46:28 PM,"(41.685543881, -87.616812541)"
7748355,12847324,09/27/2022 11:00:00 AM,THEFT,OVER $500,RESIDENCE,False,False,331,3.00,5.00,41.77,-87.57,JF420102,023XX E 70TH ST,0810,43.00,06,"1,193,181.00","1,859,005.00","2,022.00",01/03/2023 03:46:28 PM,"(41.768068052, -87.567452932)"
7748356,12847570,09/03/2022 10:25:00 AM,NARCOTICS,POSSESS - BARBITURATES,RESIDENCE - YARD (FRONT / BACK),True,False,1623,16.00,45.00,41.97,-87.76,JF420427,052XX W CARMEN AVE,2021,11.00,18,"1,140,553.00","1,933,418.00","2,022.00",01/03/2023 03:46:28 PM,"(41.973391184, -87.758534512)"
7748357,12840464,09/26/2022 07:20:00 PM,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,SIDEWALK,True,False,1513,15.00,29.00,41.88,-87.77,JF411839,0000X N MASON AVE,143A,25.00,15,"1,136,773.00","1,899,652.00","2,022.00",01/03/2023 03:46:28 PM,"(41.880802263, -87.773245737)"

In [20]:
years = df['Date'].map(lambda x: x.split()[0].split('/')[-1])
years.value_counts().sort_index()

2001    971744
2002    973602
2003    951958
2004    938840
2005    907538
2006    896348
2007    874162
2008    854318
2009    785632
2010    740984
2011    703918
2012    672520
2013    614924
2014    551450
2015    529474
2016    539556
2017    538098
2018    537496
2019    522426
2020    424082
2021    416878
2022    474406
2023     76362
Name: Date, dtype: int64

## Summary

- The chicago crime dataset has now been saved to your repository as csv files. 
- You should save your notebook, commit your work and push to GitHub using GitHub desktop.

## Question 1 - Comparing Police Districts

In [21]:
q1_df = df.copy()
q1_df.head()

In [22]:
q1_df['Datetime'] = pd.to_datetime(df['Date'])

In [23]:
q1_df['District'].value_counts()

8.00     1041840
11.00     995262
6.00      905858
7.00      897576
25.00     881888
4.00      879888
3.00      785990
12.00     766840
9.00      757670
2.00      733264
19.00     695128
18.00     694998
5.00      687164
10.00     667612
15.00     665072
1.00      625288
14.00     599880
16.00     518104
22.00     507932
24.00     467840
17.00     447248
20.00     273808
31.00        464
21.00          8
Name: District, dtype: int64

District 8 has the most crime, and district 21 has the least crime.

## Question 2 - Crimes Across the Years

In [25]:
q1_df['Year'] = q1_df['Datetime'].dt.year
q1_df['Year'].value_counts()

2002    973602
2001    971744
2003    951958
2004    938840
2005    907538
2006    896348
2007    874162
2008    854318
2009    785632
2010    740984
2011    703918
2012    672520
2013    614924
2014    551450
2016    539556
2017    538098
2018    537496
2015    529474
2019    522426
2022    474406
2020    424082
2021    416878
2023     76362
Name: Year, dtype: int64

The total amount of crime is decreasing over the years

## Question 4 - Comparing Months

In [27]:
q1_df['Month'] = q1_df['Datetime'].dt.month
q1_df['Month'].value_counts()

7     1433974
8     1420310
5     1365460
6     1363016
10    1352040
9     1335892
3     1259042
4     1253904
1     1243090
11    1217406
12    1158850
2     1093732
Name: Month, dtype: int64

July has the most crime while February has the least crime.